### ISSUE TITLE
Move `example*.tex` and `files/` from `/` to `/examples/`

### ISSUE THREAD

**Issue by Witiko** [drehak/pandoc-to-markdown#5]
The root directory of the project is starting to look hairy.

## Tasks
- [x] Create directory `examples/`
- [x] Move `example-*.tex` and `Makefile` to `examples/`.
       Drop the leading `example-` from the filenames, [fix `Makefile`][1], and [update usage instructions in `README.md`][2].
- [x] Move `files/README.md` to `examples/`.
- [x] Move `files/` to `examples/`.
- [x] Fix `.github/workflows/main.yml`.

 [1]: https://github.com/drehak/pandoc-to-markdown/issues/5#issuecomment-1112261996
 [2]: https://github.com/drehak/pandoc-to-markdown/issues/5#issuecomment-1112262052

**Comment by Witiko** [comment]
To allow the use of `*.sty` and `*.tex` files from the root directory, `examples/Makefile` should execute `latexmk` with the `TEXINPUTS=.:..:` environmental variable exported.

**Comment by Witiko** [comment]
Here is how the updated compile instructions would look like:

> To typeset the example documents, execute the following command on a system with
an up-to-date installation of TeX Live and Pandoc:
>
>     $ make -C examples
>
> Alternatively, you can use [the witiko/markdown Docker image][5], which includes
both TeX Live and Pandoc:
>
>     $ docker run --rm -it -v "$PWD":/workdir -w /workdir witiko/markdown \
>     > latexmk -shell-escape -pdf examples/man-pandoc.tex

 [5]: https://hub.docker.com/r/witiko/markdown/tags

**Comment by drehak** [comment]
All done.
